# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-deployment
  template:
    metadata:
      labels:
        app: mlflow-deployment
    spec:
      volumes:
        - name: mlflow-pvc
          persistentVolumeClaim:
            claimName: mlflow-pvc
      containers:
      - name: mlflow-deployment
        image: dkhundley/mlflow-server
        imagePullPolicy: Always
        args:
        - --host=0.0.0.0
        - --port=80
        # - --backend-store-uri=/opt/mlflow/backend/
        # - --default-artifact-root=/opt/mlflow/artifacts/
        - --workers=2
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: mlflow-pvc
          mountPath: /opt/mlflow/
